name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Get Version
        id: vars
        run: echo ::set-output name=version::$(echo ${{github.ref_name}} | sed 's/^v//')

      - name: Build JSR
        run: deno task build:jsr ${{steps.vars.outputs.version}}

      - name: Publish JSR
        run: deno publish --allow-dirty --token=${{secrets.JSR_TOKEN}}
